### PR TITLE
Migration

### PR DESCRIPTION
**Pull request by wmedders21**
### Why?
```
Created a db migration to app.sqlite 
```

### Final checklist:

```
[x] I have reviewed my code
[ ] I have comments in my code for better understanding if needed
[ ] I have tested my code
```

### Memes:
image

### CODE REVIEW

**Comment by B-gann21** [comment]
So far the Models.py cover all the tables/columns we will need in the DB. Looks good!

For now using SQLite is fine, I recall you ran into errors trying to get PostgreSQL set up. SQLite should do everything we need it to just fine, but I'm open to suggestions from Khoa. 

Once our project mentor reviews this I think it should be fine to merge

**Review by johnny-bowman — APPROVED** [review]
I support moving to SQLite. Would love to hear what Khoa says!

**Comment by omegaeye-he** [comment]
SQLite sounds great to me.

**Comment by omegaeye-he** [comment]
What's with the 5000+ files changed ... that's concerning

**Comment by wmedders21** [comment]
@omegaeye-he You said you wanted small PRs lol. JK I deleted a venv folder and added a different one. All the files are in there.

**Pull request closed without merging**
