### PR TITLE
Added sample test

### PR DESCRIPTION
**Pull request by wmedders21**
### Why?:
```
Just adding a passing test in order to configure CI
```
### Function Checks:
```
[x] All tests passing
[x] Code runs locally
```

### Type of Change:

```
[x] New Feature
[ ] Bug fix
```

### Implementation/Fix Details:

```
Just adding a passing test in order to configure CI
```

### Dummy check: Did this break anything else?

```
[ ] Yes
[x] No
```
### Final checklist:

```
[x] I have reviewed my code
[ ] I have comments in my code for better understanding if needed
[ ] I have tested my code
```

### CODE REVIEW

**Review by Reuben-Davison — APPROVED** [review]
A very comprehensive PR with test. Good job on getting circle CI up and running.

**Comment by omegaeye-he** [comment]
Looks good, but the commit needs a body to explain why even if it's redundant.

**Comment by wmedders21** [comment]
@Omegaeye is this what you mean?

**Comment by B-gann21** [comment]
Looks good to me. Smart getting the file structure set up for circleCI, should make the transition pretty smooth when we add more functionality!

**Pull request closed without merging**
